name: turkish-news-feeder
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - annotated-types=0.7.0
  - anyio=4.6.2.post1
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - distro=1.9.0
  - exceptiongroup=1.2.2
  - feedparser=6.0.11
  - groq=0.12.0
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.7
  - httpx=0.27.2
  - hyperframe=6.0.1
  - idna=3.10
  - ld_impl_linux-64=2.43
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libiconv=1.17
  - libnsl=2.0.1
  - libsqlite=3.47.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzlib=1.3.1
  - lxml=5.3.0
  - ncurses=6.5
  - openssl=3.4.0
  - pip=24.3.1
  - pydantic=2.9.2
  - pydantic-core=2.23.4
  - python=3.12.7
  - python-dotenv=1.0.1
  - python_abi=3.12
  - readline=8.2
  - setuptools=75.5.0
  - sgmllib3k=1.0.0
  - sniffio=1.3.1
  - tk=8.6.13
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - wheel=0.45.0
  - xz=5.2.6
